### ISSUE TITLE
T1 download tool out of date

### ISSUE THREAD

**Issue by The-Kergan** [zuedev/coronavirus-toolkit#127]
**Describe the bug**
Tool T1 download button links to an out of date pdf version.

**Action**
Sorry @Nelviticus - not being able to upload files is a pita.

`T1-Coronavirus_Symptom_Tracker-v4.pdf` in GitHub repo needs to be replaced by `T1-Coronavirus_Symptom_Tracker-v5.pdf` currently in dropbox.

`Dropbox\COVID-19\1-WORK OUTPUT\WEEK 3\FINAL\`

Add T5 version, then delete T4 version from Public folder. Thanks.

**Comment by zuedev** [comment]
Merged, closing.
