### ISSUE TITLE
T4: Household Lockdown formatting errors

### ISSUE THREAD

**Issue by The-Kergan** [zuedev/coronavirus-toolkit#30]
See screen grab

![2020-03-31 10_14_26-F1_ Preparing for Coronavirus Lock-Down _ Coronavirus Toolkit - Opera](https://user-images.githubusercontent.com/44531202/78036747-a9a8db80-7338-11ea-8b8c-be4c1afaa378.jpg)

**Comment by geoffwasham** [comment]
Pull request submitted: https://github.com/zeue/coronavirus-toolkit/pull/41
