### ISSUE TITLE
Website Enhancements

### ISSUE THREAD

**Issue by The-Kergan** [zuedev/coronavirus-toolkit#34]
**Is your feature request related to a problem? Please describe.**
The site is now rapidly achieving minimum standards and fitness for purpose. However we still need an plan to improve and maintain it.

**Describe the solution you'd like**
1. A plan of priorities, such as
2. Measurement of visits/source & downloads
3. Registration for updates
4. Clear tool version / change history and pushes to registered people
5. Comments / suggestions / error notifications per Tool and Focus
6. 'Submit a tool' process
7. 'Volunteer your time' recruitment process
8. CRM to automate social outreach to registered users
9. etc

**Suggested Next steps**
Alex to schedule a meeting with Geoff, me and others to brainstorm features and discuss priorities for the plan - Alex is this OK?

**Comment by zeue** [comment]
@The-Kergan Yes this is okay, transitioning to Slack for scheduling.

**Comment by zuedev** [comment]
Moving to Trello, closing here
